### ISSUE TITLE
Problems building aleoncean-openhab-binding jar

### ISSUE THREAD

**Issue by sepp99** [aleon-GmbH/aleoncean-openhab-binding#17]
Hi all,
I tried to build the binding with different combinations of aleoncean and aleoncean-openhab-binding (Maven). The build itself works but the resulting jar file does not contain the lib/aleoncean-xxx.jar. The jar "org.openhab.binding.aleoncean-1.6.0-SNAPSHOT.jar" (I found on the web) contains that file. When I copy the jar into the OpenHab addons dir nothing happens.
So maybe someone can give me a hint, what's going wrong.

Thanks in advance,
Christoph

**Comment by maggu2810** [comment]
> The build itself works but the resulting jar file does not contain the lib/aleoncean-xxx.jar

Ok, this is the correct and expected behaviour.

> The jar "org.openhab.binding.aleoncean-1.6.0-SNAPSHOT.jar" (I found on the web) contains that file.

That is a rather old version and library handling changed.

> When I copy the jar into the OpenHab addons dir nothing happens.

You have to add the aleoncean bundle and the aleoncean-openhab-binding to your OSGi environment.

**Comment by sepp99** [comment]
I finally managed to get it working with OpenHAB 2.0.0b2 and the following combination:
aleoncean-1.9.jar
org.openhab.binding.aleoncean-1.7.5-SNAPSHOT.jar
No other combination I tried works with b2.

I also tried the stable version of OpenHAB 1.8.1 with
aleoncean-1.8.jar
org.openhab.binding.aleoncean-1.7.3.jar
(which according to github should be the last possible version)
With that two modules nothing happens, no error or debug messages. If I copy the "org.openhab.binding.aleoncean-1.6.0-SNAPSHOT.jar" into addons the binding starts and is working (aleoncean binding has been started.).

Help is appreciated.

**Comment by maggu2810** [comment]
> I also tried the stable version of OpenHAB 1.8.1

As stated in the README.md file (it should be displayed on the landing page: https://github.com/aleon-GmbH/aleoncean-openhab-binding), the support of plain OH1 has been dropped some time ago.

I am not using OH2 myself anymore.
But there are other ones that have it running.

@kungfoolfighting, @denniseffing, @jrcourtois, @mccare Could someone of you help this guy?

I am not a friend of the addons folder OH2 is using because bundles removed from this folder are not uninstalled / removed from the runtime.

Some instruction that should help:
* ensure the openHAB compat1x feature and the serial transport feature are installed (feature:install)
* use <code>bundle:list -s -t 0</code> to get a list of installed bundles
* use <code>bundle:uninstall ...</code> to uninstall all aleoncean libraries / bindings
* use <code>bundle:install -s ... </code> to install (and start) the recent version (you build) of the aleoncean library / binding
* configure your USB port (e.g. aleoncean.cfg)
* ...

For help about the "common" (not aleoncean specific) stuff you could read the Karaf commands or use the openHAB community.

If the port is configured, only 1 library and 1 binding is installed, and both are started, I would assume it should work.

**Comment by denniseffing** [comment]
I am running the binding with openHAB 2.0.0b2 with the following versions:
aleoncean 1.9
aleoncean-binding 1.7.4

As maggu2810 already stated, you have to copy the API and the binding in the openHAB 2 addons folder.

1.7.4 is the latest version according to the releases here on github.
See https://github.com/aleon-GmbH/aleoncean-openhab-binding/releases
If you need any help compiling the sources properly, let me know but I guess you already figured that out.

Is there any particular reason you want to run the binding on openHAB 1.8.1?

**Comment by kungfoolfighting** [comment]
You want to just compile the head revisions of both the openhab binding and the aleoncean library.
You don't have to put them in the plugins directory actually, you can install and start both of them via the Karaf console.

**Comment by sepp99** [comment]
@maggu2810, @denniseffing 
The hint with "bundle:uninstall" (or freshly unzip openhab2) did it. That's why I wasn't able to get back from 1.7.5-SNAPSHOT. Now I have it working with aleoncean 1.9 and aleoncean-binding 1.7.4.

Regarding OH 1.8.1: I didn't manage to get it working with neither combination of aleoncean + aleoncean-binding. I thought to begin with a stable version of OH. But as 2.0.0b2 works out quite well, I think I'll stick with b2.

Thanks you all for your help!
